version: '2'

networks:
    podcast_clips:

services:
    nginx:
        image: nginx:stable-alpine
        restart: unless-stopped
        container_name: podcast_clips_nginx
        ports:
            - "8889:80"
        volumes:
            - ./code:/var/www/code
            - ./podcasts:/var/www/podcasts
            - ./clips:/var/www/clips
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        environment:
            TZ: America/Vancouver
        depends_on:
            - php
        networks:
            - podcast_clips

    mariaDB:
        image: mariadb:11
        restart: unless-stopped
        container_name: podcast_clips_mariaDB
        volumes:
            - ./database:/var/lib/mysql:rw
            - ./setupdb:/docker-entrypoint-initdb.d
        environment:
            MARIADB_AUTO_UPGRADE: 1
            TZ: America/Vancouver
            #root password is stored in .env, change it to a secure password
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        command:
            - "mariadbd"
            - "--innodb_buffer_pool_size=400M"
            - "--innodb-ft-min-token-size=2"
            - "--innodb-ft-enable-stopword=off"
        depends_on:
            - nginx
        networks:
            - podcast_clips

    php:
        build:
          context: ./Dockerfile_php
        restart: unless-stopped
        container_name: podcast_clips_php
        user: "1000:1000"
        volumes:
            - ./code:/var/www/code
            - ./podcasts:/var/www/podcasts
            - ./clips:/var/www/clips
            - ./connect.php:/var/connect.php
        environment:
            TZ: America/Vancouver
        expose:
            - "9000"
        networks:
            - podcast_clips

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        container_name: podcast_clips_phpMyAdmin
        ports:
            - "8183:80"
        environment:
            TZ: America/Vancouver
            PMA_ARBITRARY: 1
        depends_on:
            - mariaDB
        networks:
            - podcast_clips

    db-backup:
        container_name: podcast_clips_db_backup
        image: ghcr.io/tiredofit/docker-db-backup
        volumes:
            - ./backups:/backup
        environment:
            - CONTAINER_ENABLE_MONITORING=FALSE
            - DB_TYPE=mariadb
            - DB_HOST=podcast_clips_mariaDB
            - DB_NAME=ALL
            - DB_NAME_EXCLUDE=mysql,sys
            - DB_USER=root
            - DB_PASS=${MYSQL_ROOT_PASSWORD}
            - DEFAULT_BACKUP_INTERVAL=1440
            - DEFAULT_BACKUP_BEGIN=0300
            - DB_CLEANUP_TIME=8640
            - DEFAULT_COMPRESSION=XZ
            - DEFAULT_COMPRESSION_LEVEL=9
            - TZ=America/Vancouver
        restart: unless-stopped
        depends_on:
            - mariaDB
        networks:
            - podcast_clips
