version: '2'

networks:
    podcast_clips:

services:
    nginx:
        build:
          context: ./Dockerfile_nginx
        restart: unless-stopped
        container_name: podcast_clips_nginx
        ports:
            - "8889:80"
        volumes:
            - ./code:/var/www/code
            - ./podcasts:/var/www/podcasts
            - ./clips:/var/www/clips
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - podcast_clips

    mariaDB:
        image: mariadb:latest
        restart: unless-stopped
        container_name: podcast_clips_mariaDB
        volumes:
            - ./database:/var/lib/mysql:rw
            - ./setupdb:/docker-entrypoint-initdb.d
        depends_on:
            - nginx
        #root password is stored in .env_mariadb, change it to a secure password
        env_file:
            - .env_mariadb
        networks:
            - podcast_clips    

    php:
        build:
          context: ./Dockerfile_php
        restart: unless-stopped
        container_name: podcast_clips_php
        volumes:
            - ./code:/var/www/code
            - ./podcasts:/var/www/podcasts
            - ./connect.php:/var/connect.php
        expose:
            - "9000"       
        networks:
            - podcast_clips

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        container_name: podcast_clips_phpMyAdmin
        ports:
            - "8183:80"
        environment:        
            PMA_ARBITRARY: 1
        depends_on:
            - mariaDB
        networks:
            - podcast_clips
